import { garageMasterT } from "../types/garageMasterT";

export const garageMasterData: garageMasterT[] = [
  {
    name: "garage1",
    contact: "1111111111",
    email: "garage1@gmail.com",
    thumbnail: "garageImages/image1.jpg",
    open_time: "08:00 AM",
    close_time: "06:00 PM",
    description: "A shelter or repair shop for automotive vehicles.",
    status: true,
  },
  {
    name: "garage2",
    contact: "2222222222",
    email: "garage2@gmail.com",
    thumbnail: "garageImages/image2.jpg",
    open_time: "09:00 AM",
    close_time: "07:00 PM",
    description:
      "A cabinet with a vertical rolling door for small kitchen appliances.",
    status: false,
  },
  {
    name: "garage3",
    contact: "3333333333",
    email: "garage3@gmail.com",
    thumbnail: "garageImages/image3.jpg",
    open_time: "07:30 AM",
    close_time: "05:30 PM",
    description: "A repair shop specializing in luxury vehicles.",
    status: true,
  },
  {
    name: "garage4",
    contact: "4444444444",
    email: "garage4@gmail.com",
    thumbnail: "garageImages/image4.jpg",
    open_time: "10:00 AM",
    close_time: "08:00 PM",
    description: "Automotive repair and maintenance services.",
    status: false,
  },
  {
    name: "garage5",
    contact: "5555555555",
    email: "garage5@gmail.com",
    thumbnail: "garageImages/image5.jpg",
    open_time: "08:30 AM",
    close_time: "06:30 PM",
    description: "Specialized in electric vehicle repairs.",
    status: true,
  },
  {
    name: "garage6",
    contact: "6666666666",
    email: "garage6@gmail.com",
    thumbnail: "garageImages/image6.jpg",
    open_time: "09:30 AM",
    close_time: "07:30 PM",
    description: "Offering 24/7 roadside assistance.",
    status: false,
  },
  {
    name: "garage7",
    contact: "7777777777",
    email: "garage7@gmail.com",
    thumbnail: "garageImages/image7.jpg",
    open_time: "07:00 AM",
    close_time: "05:00 PM",
    description: "Specialized in vintage car restorations.",
    status: true,
  },
  {
    name: "garage8",
    contact: "8888888888",
    email: "garage8@gmail.com",
    thumbnail: "garageImages/image8.jpg",
    open_time: "10:30 AM",
    close_time: "08:30 PM",
    description: "Complete automotive diagnostics and repairs.",
    status: false,
  },
  {
    name: "garage9",
    contact: "9999999999",
    email: "garage9@gmail.com",
    thumbnail: "garageImages/image9.jpg",
    open_time: "08:00 AM",
    close_time: "06:00 PM",
    description: "Advanced automotive technology services.",
    status: true,
  },
  {
    name: "garage10",
    contact: "1010101010",
    email: "garage10@gmail.com",
    thumbnail: "garageImages/image10.jpg",
    open_time: "09:00 AM",
    close_time: "07:00 PM",
    description: "High-performance tuning and upgrades.",
    status: false,
  },
  {
    name: "garage11",
    contact: "1111111110",
    email: "garage11@gmail.com",
    thumbnail: "garageImages/image11.jpg",
    open_time: "08:00 AM",
    close_time: "06:00 PM",
    description: "State-of-the-art automotive service center.",
    status: true,
  },
  {
    name: "garage12",
    contact: "1212121212",
    email: "garage12@gmail.com",
    thumbnail: "garageImages/image12.jpg",
    open_time: "10:00 AM",
    close_time: "08:00 PM",
    description: "Automotive repair shop with expert technicians.",
    status: false,
  },
  {
    name: "garage13",
    contact: "1313131313",
    email: "garage13@gmail.com",
    thumbnail: "garageImages/image13.jpg",
    open_time: "07:30 AM",
    close_time: "05:30 PM",
    description: "Specializing in quick oil changes and maintenance.",
    status: true,
  },
  {
    name: "garage14",
    contact: "1414141414",
    email: "garage14@gmail.com",
    thumbnail: "garageImages/image14.jpg",
    open_time: "09:00 AM",
    close_time: "07:00 PM",
    description: "Comprehensive tire services and alignments.",
    status: false,
  },
  {
    name: "garage15",
    contact: "1515151515",
    email: "garage15@gmail.com",
    thumbnail: "garageImages/image15.jpg",
    open_time: "08:30 AM",
    close_time: "06:30 PM",
    description: "Certified auto body repair and painting.",
    status: true,
  },
  {
    name: "garage16",
    contact: "1616161616",
    email: "garage16@gmail.com",
    thumbnail: "garageImages/image16.jpg",
    open_time: "07:00 AM",
    close_time: "05:00 PM",
    description: "Emergency towing and repair services.",
    status: false,
  },
  {
    name: "garage17",
    contact: "1717171717",
    email: "garage17@gmail.com",
    thumbnail: "garageImages/image17.jpg",
    open_time: "10:00 AM",
    close_time: "08:00 PM",
    description: "Expert vehicle diagnostics and repairs.",
    status: true,
  },
  {
    name: "garage18",
    contact: "1818181818",
    email: "garage18@gmail.com",
    thumbnail: "garageImages/image18.jpg",
    open_time: "08:00 AM",
    close_time: "06:00 PM",
    description: "Affordable auto repair and maintenance.",
    status: false,
  },
  {
    name: "garage19",
    contact: "1919191919",
    email: "garage19@gmail.com",
    thumbnail: "garageImages/image19.jpg",
    open_time: "07:30 AM",
    close_time: "05:30 PM",
    description: "High-quality parts and expert service.",
    status: true,
  },
  {
    name: "garage20",
    contact: "2020202020",
    email: "garage20@gmail.com",
    thumbnail: "garageImages/image20.jpg",
    open_time: "09:00 AM",
    close_time: "07:00 PM",
    description: "Performance enhancements and tuning.",
    status: false,
  },
  {
    name: "garage21",
    contact: "2121212121",
    email: "garage21@gmail.com",
    thumbnail: "garageImages/image21.jpg",
    open_time: "08:00 AM",
    close_time: "06:00 PM",
    description: "Expert brake service and repair.",
    status: true,
  },
  {
    name: "garage22",
    contact: "2222222222",
    email: "garage22@gmail.com",
    thumbnail: "garageImages/image22.jpg",
    open_time: "10:00 AM",
    close_time: "08:00 PM",
    description: "Certified mechanics for all car models.",
    status: false,
  },
  {
    name: "garage23",
    contact: "2323232323",
    email: "garage23@gmail.com",
    thumbnail: "garageImages/image23.jpg",
    open_time: "07:00 AM",
    close_time: "05:00 PM",
    description: "Complete automotive care and repair.",
    status: true,
  },
  {
    name: "garage24",
    contact: "2424242424",
    email: "garage24@gmail.com",
    thumbnail: "garageImages/image24.jpg",
    open_time: "09:00 AM",
    close_time: "07:00 PM",
    description: "Trusted auto repair shop for over 20 years.",
    status: false,
  },
  {
    name: "garage25",
    contact: "2525252525",
    email: "garage25@gmail.com",
    thumbnail: "garageImages/image25.jpg",
    open_time: "08:30 AM",
    close_time: "06:30 PM",
    description: "Advanced diagnostics and repair services.",
    status: true,
  },
  {
    name: "garage26",
    contact: "2626262626",
    email: "garage26@gmail.com",
    thumbnail: "garageImages/image26.jpg",
    open_time: "07:00 AM",
    close_time: "05:00 PM",
    description: "Expert tire fitting and wheel balancing.",
    status: false,
  },
  {
    name: "garage27",
    contact: "2727272727",
    email: "garage27@gmail.com",
    thumbnail: "garageImages/image27.jpg",
    open_time: "10:00 AM",
    close_time: "08:00 PM",
    description: "Professional car detailing services.",
    status: true,
  },
  {
    name: "garage28",
    contact: "2828282828",
    email: "garage28@gmail.com",
    thumbnail: "garageImages/image28.jpg",
    open_time: "08:00 AM",
    close_time: "06:00 PM",
    description: "Specialized in transmission repairs.",
    status: false,
  },
  {
    name: "garage29",
    contact: "2929292929",
    email: "garage29@gmail.com",
    thumbnail: "garageImages/image29.jpg",
    open_time: "07:30 AM",
    close_time: "05:30 PM",
    description: "Your one-stop shop for auto repair.",
    status: true,
  },
  {
    name: "garage30",
    contact: "3030303030",
    email: "garage30@gmail.com",
    thumbnail: "garageImages/image30.jpg",
    open_time: "09:00 AM",
    close_time: "07:00 PM",
    description: "Quality repairs at affordable prices.",
    status: false,
  },
  {
    name: "garage31",
    contact: "3131313131",
    email: "garage31@gmail.com",
    thumbnail: "garageImages/image31.jpg",
    open_time: "08:00 AM",
    close_time: "06:00 PM",
    description: "Experienced mechanics for all your needs.",
    status: true,
  },
  {
    name: "garage32",
    contact: "3232323232",
    email: "garage32@gmail.com",
    thumbnail: "garageImages/image32.jpg",
    open_time: "10:00 AM",
    close_time: "08:00 PM",
    description: "Expert engine diagnostics and repair.",
    status: false,
  },
  {
    name: "garage33",
    contact: "3333333333",
    email: "garage33@gmail.com",
    thumbnail: "garageImages/image33.jpg",
    open_time: "07:00 AM",
    close_time: "05:00 PM",
    description: "Full-service automotive repair shop.",
    status: true,
  },
  {
    name: "garage34",
    contact: "3434343434",
    email: "garage34@gmail.com",
    thumbnail: "garageImages/image34.jpg",
    open_time: "09:00 AM",
    close_time: "07:00 PM",
    description: "Certified auto repair and maintenance.",
    status: false,
  },
  {
    name: "garage35",
    contact: "3535353535",
    email: "garage35@gmail.com",
    thumbnail: "garageImages/image35.jpg",
    open_time: "08:30 AM",
    close_time: "06:30 PM",
    description: "Affordable and reliable auto service.",
    status: true,
  },
  {
    name: "garage36",
    contact: "3636363636",
    email: "garage36@gmail.com",
    thumbnail: "garageImages/image36.jpg",
    open_time: "07:00 AM",
    close_time: "05:00 PM",
    description: "Expert suspension and alignment services.",
    status: false,
  },
  {
    name: "garage37",
    contact: "3737373737",
    email: "garage37@gmail.com",
    thumbnail: "garageImages/image37.jpg",
    open_time: "10:00 AM",
    close_time: "08:00 PM",
    description: "Comprehensive vehicle inspections.",
    status: true,
  },
  {
    name: "garage38",
    contact: "3838383838",
    email: "garage38@gmail.com",
    thumbnail: "garageImages/image38.jpg",
    open_time: "08:00 AM",
    close_time: "06:00 PM",
    description: "Specialized in hybrid vehicle repairs.",
    status: false,
  },
  {
    name: "garage39",
    contact: "3939393939",
    email: "garage39@gmail.com",
    thumbnail: "garageImages/image39.jpg",
    open_time: "07:30 AM",
    close_time: "05:30 PM",
    description: "Fast and reliable car repairs.",
    status: true,
  },
  {
    name: "garage40",
    contact: "4040404040",
    email: "garage40@gmail.com",
    thumbnail: "garageImages/image40.jpg",
    open_time: "09:00 AM",
    close_time: "07:00 PM",
    description: "Expert auto body repairs and refinishing.",
    status: false,
  },
  {
    name: "garage41",
    contact: "4141414141",
    email: "garage41@gmail.com",
    thumbnail: "garageImages/image41.jpg",
    open_time: "08:00 AM",
    close_time: "06:00 PM",
    description: "Professional auto glass repair and replacement.",
    status: true,
  },
  {
    name: "garage42",
    contact: "4242424242",
    email: "garage42@gmail.com",
    thumbnail: "garageImages/image42.jpg",
    open_time: "10:00 AM",
    close_time: "08:00 PM",
    description: "Certified automotive repair and service.",
    status: false,
  },
  {
    name: "garage43",
    contact: "4343434343",
    email: "garage43@gmail.com",
    thumbnail: "garageImages/image43.jpg",
    open_time: "07:00 AM",
    close_time: "05:00 PM",
    description: "Reliable and affordable car repair services.",
    status: true,
  },
  {
    name: "garage44",
    contact: "4444444444",
    email: "garage44@gmail.com",
    thumbnail: "garageImages/image44.jpg",
    open_time: "09:00 AM",
    close_time: "07:00 PM",
    description: "Specializing in diesel engine repairs.",
    status: false,
  },
  {
    name: "garage45",
    contact: "4545454545",
    email: "garage45@gmail.com",
    thumbnail: "garageImages/image45.jpg",
    open_time: "08:30 AM",
    close_time: "06:30 PM",
    description: "Quality auto repairs by certified technicians.",
    status: true,
  },
  {
    name: "garage46",
    contact: "4646464646",
    email: "garage46@gmail.com",
    thumbnail: "garageImages/image46.jpg",
    open_time: "07:00 AM",
    close_time: "05:00 PM",
    description: "Complete vehicle maintenance and repair.",
    status: false,
  },
  {
    name: "garage47",
    contact: "4747474747",
    email: "garage47@gmail.com",
    thumbnail: "garageImages/image47.jpg",
    open_time: "10:00 AM",
    close_time: "08:00 PM",
    description: "Full-service tire shop and auto repair.",
    status: true,
  },
  {
    name: "garage48",
    contact: "4848484848",
    email: "garage48@gmail.com",
    thumbnail: "garageImages/image48.jpg",
    open_time: "08:00 AM",
    close_time: "06:00 PM",
    description: "Expert automotive diagnostics and repairs.",
    status: false,
  },
  {
    name: "garage49",
    contact: "4949494949",
    email: "garage49@gmail.com",
    thumbnail: "garageImages/image49.jpg",
    open_time: "07:30 AM",
    close_time: "05:30 PM",
    description: "Reliable and efficient car maintenance services.",
    status: true,
  },
  {
    name: "garage50",
    contact: "5050505050",
    email: "garage50@gmail.com",
    thumbnail: "garageImages/image50.jpg",
    open_time: "09:00 AM",
    close_time: "07:00 PM",
    description: "High-quality automotive repair and maintenance.",
    status: false,
  },
];
